### ISSUE TITLE
sqlancer stops generating new queries when deployed to test an existing database

### ISSUE THREAD

**Issue by xinyuliu12** [sqlancer/sqlancer#271] opened 2020-12-15 03:46 UTC
I followed hints from #267 to try to generate random queries based on an existing sqlite3 database. 
However, sqlancer will stop generating queries after generating the first few queries.

An example snapshot for the stdout is as follows:
`$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --timeout-seconds=60 --print-statements True --num-threads 1 sqlite3 --execute-queries=False --oracle QUERY_PARTITIONING --generate-new-database false`
[2020/12/14 22:34:33] Executed 2 queries (0 queries/s; 0.20/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:34:38] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:34:43] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:34:48] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:34:53] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:34:58] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:03] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:08] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:13] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:18] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:23] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.
[2020/12/14 22:35:28] Executed 2 queries (0 queries/s; 0.00/s dbs, successful statements: 75%). Threads shut down: 0.

An example content of the logfile is as follows:
```
SELECT ALL REGION.R_NAME, PART.P_CONTAINER, SUPPLIER.S_NAME, PART.P_BRAND, SUPPLIER.S_ADDRESS FROM SUPPLIER, PART LEFT OUTER JOIN REGION ON ((LIKELIHOOD(SUPPLIER.S_NAME, REGION.R_NAME))||(x''));
SELECT DISTINCT SUPPLIER.S_COMMENT, SUPPLIER.S_NATIONKEY, SUPPLIER.S_ADDRESS FROM SUPPLIER;
SELECT DISTINCT SUPPLIER.S_COMMENT, SUPPLIER.S_NATIONKEY, SUPPLIER.S_ADDRESS FROM SUPPLIER WHERE ((((SUPPLIER.S_COMMENT IN (SUPPLIER.S_NAME)))+(CASE WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_PHONE THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_ACCTBAL THEN SUPPLIER.S_COMMENT END))) UNION SELECT DISTINCT SUPPLIER.S_COMMENT, SUPPLIER.S_NATIONKEY, SUPPLIER.S_ADDRESS FROM SUPPLIER WHERE ((NOT ((((SUPPLIER.S_COMMENT IN (SUPPLIER.S_NAME)))+(CASE WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_PHONE THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_ACCTBAL THEN SUPPLIER.S_COMMENT END))))) UNION SELECT DISTINCT SUPPLIER.S_COMMENT, SUPPLIER.S_NATIONKEY, SUPPLIER.S_ADDRESS FROM SUPPLIER WHERE ((((((SUPPLIER.S_COMMENT IN (SUPPLIER.S_NAME)))+(CASE WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_NAME THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_PHONE THEN SUPPLIER.S_COMMENT WHEN SUPPLIER.S_ACCTBAL THEN SUPPLIER.S_COMMENT END))) ISNULL));
SELECT CUSTOMER.C_CUSTKEY FROM CUSTOMER, PART, REGION, SUPPLIER, NATION GROUP BY CUSTOMER.C_CUSTKEY;
```

**Expected Behavior**

I would have expected sqlancer to generate many random queries based on the existing schema.

**Reproduce Bug**

1. set up a TPCH.db (download using the following link: https://drive.google.com/file/d/17QXAJoSbQiqoOajjiBDALavZg7U0swTH/view?usp=sharing)

2. change code in SQLite3Provider.java following hints from #267  

- Specifically, change the url in function `createDatabase` in order to connect to an existing database https://github.com/sqlancer/sqlancer/blob/0b7c724743a77c8fdee84fa70262fd0a278b681a/src/sqlancer/sqlite3/SQLite3Provider.java#L285
- You can download the resulting SQLite3Provider.java using the following link (https://drive.google.com/file/d/1KCs2fJkNDA9FdsqsIuu4_UUMmF0k_-A9/view?usp=sharing) (you still need to add your own absolute path of the `TPCH.db` in function `createDatabase`)

3. Build the new sqlancer

`mvn package -DskipTests
`

3. run the sqlancer using the following command (setting `--generate-new-database` to be false to avoid modifying the existing database) 

`
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --timeout-seconds=60 --print-statements True --num-threads 1 sqlite3 --execute-queries=False --oracle QUERY_PARTITIONING --generate-new-database false
`

It would be extremely helpful if you could provide any suggestion on how to fix this bug or point out if I was using the wrong command to fulfill my goal. Thank you!!!

**Comment by mrigger** [comment] 2020-12-15 09:37
Thanks for the detailed report! The problem is that the last query does not terminate (in reasonable time):

```sql
SELECT CUSTOMER.C_CUSTKEY FROM CUSTOMER, PART, REGION, SUPPLIER, NATION GROUP BY CUSTOMER.C_CUSTKEY;
``` 

To compute the ground truth, TLP relies on querying all rows from the cross product of the selected tables, and the result set explodes in this case. SQLancer itself only creates tables with few rows, to make all queries execute quickly and thus is not affected by this issue. Depending on your use case, I see the following three options:
* You could delete records from the tables so that the size of the cross product of all tables does not "explode" (perhaps by restricting it to a size of 10,000).
* You could add a check to SQLancer that validates that the cross product of the selected tables and views does not exceed a certain size. You could implement this here:
https://github.com/sqlancer/sqlancer/blob/02a52bf2e73e9ab3d6cd77ca64b85a719236c3b2/src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPBase.java#L40
This would be suitable as an option, similar to the one that causes SQLancer to bail out when the tables are empty:
https://github.com/sqlancer/sqlancer/blob/02a52bf2e73e9ab3d6cd77ca64b85a719236c3b2/src/sqlancer/ProviderAdapter.java#L68
* You could compute the ground truth in a different way, for example, by multiplying the cardinalities and then let the partitioning queries only validate the size of the result set. This option only makes sense if you are specifically interested in using TLP.

Does that help? Also happy to chat and/or provide feedback for your specific use case, if you are interested.

**Comment by mrigger** [comment] 2020-12-15 19:41
Closing this, since this seems to have answered the question (based on our private follow-up conversation).

**Closed by mrigger** 2020-12-15 19:41 UTC
