### ISSUE TITLE
Incorrect speed logging

### ISSUE THREAD

**Issue by qoega** [sqlancer/sqlancer#90] opened 2020-07-08 08:19 UTC
https://travis-ci.com/github/sqlancer/sqlancer/jobs/358720280

[2020/07/08 08:17:24] Executed 61181 queries (30 queries/s; 2.20/s dbs, successful statements: 56%). Threads shut down: 4.
[2020/07/08 08:17:24] Executed 61184 queries (**12236 queries/s**; 197.00/s dbs, successful statements: 56%). Threads shut down: 4.
[2020/07/08 08:17:29] Executed 61395 queries (43 queries/s; 1.20/s dbs, successful statements: 56%). Threads shut down: 4.

**Comment by mrigger** [comment] 2020-07-08 20:02
I suspect that this issue might be specific to the ClickHouse implementation, since I haven't yet observed such an issue for the other implementations. I noticed that you call ` manager.incrementSelectQueryCount();` even when an `IgnoreMeException` is thrown: https://github.com/sqlancer/sqlancer/blob/e62224edcb43fe421dc87601f75090739e34e595/src/sqlancer/clickhouse/ClickHouseProvider.java#L144

Could this be the issue? For example, in the DuckDB implementation, the counter is not incremented in such a case:

https://github.com/sqlancer/sqlancer/blob/e62224edcb43fe421dc87601f75090739e34e595/src/sqlancer/duckdb/DuckDBProvider.java#L156

**Comment by mrigger** [comment] 2020-07-22 20:50
This might have been fixed by refactoring that factored out the common logic for calling the test oracle (see https://github.com/sqlancer/sqlancer/commit/c9a626f21a4968e4b0789db0a7bca45e770b9e6f#diff-5c10c531c6221212192b6d6fae22977cR46). Did you still encounter this issue recently? If not, I would be inclined to close this issue.

**Comment by qoega** [comment] 2020-07-23 09:16
I tried on most recent version master version (with my current changes) and have same issues.
```
[2020/07/23 12:03:52] Executed 3029 queries (16 queries/s; 3,00/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:52] Executed 3029 queries (16 queries/s; 3,00/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:52] Executed 3029 queries (15 queries/s; 3,00/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:52] Executed 3029 queries (605 queries/s; 84,92/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:57] Executed 3075 queries (9 queries/s; 1,40/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:57] Executed 3075 queries (9 queries/s; 1,40/s dbs, successful statements: 56%). Threads shut down: 0.
[2020/07/23 12:03:57] Executed 3075 queries (9 queries/s; 1,40/s dbs, successful statements: 56%). Threads shut down: 0.
```
I guess it is more correct to log this statistics at most once a second or even use larger window to calculate speed. In example there are several log records for one second.

**Comment by qoega** [comment] 2020-07-23 12:17
I see it happens when I run several tests in one run. It looks like logger is created for each new one and every logger prints once in 5 seconds.
It looks that `startProgressMonitor` should check it there is one already. Or stop it after test ended.

**Comment by mrigger** [comment] 2020-07-23 12:29
Thanks for investigating this! I see now what the issue is, and can fix it.

**Comment by mrigger** [comment] 2020-08-04 07:52
Please let me know if the PR fixed the issue.

**Closed** 2020-08-04 07:51 UTC
Labels: bug
