### ISSUE TITLE
what is that ”potential bug“ means in the output

### ISSUE THREAD

**Issue by Syang111** [sqlancer/sqlancer#897] opened 2023-10-30 12:21 UTC
I ran the command
> docker run sqlancer -v $(pwd)/datadir:/logs --num-threads 4 --use-reducer --reduce-ast  sqlite3 --oracle NoREC  

and it produced these outputs，can anyone tell me what is the ”potential bug“ means？I didnt find answers in the paper.

```
`EXPERIMENTAL: Trying to reduce queries using a simple reducer.
Error when parsing the statement at transformer :remove union selects
Error when parsing the statement at transformer :remove union selects
Error when parsing the statement at transformer :remove union selects
Error when parsing the statement at transformer :remove clauses of select
Error when parsing the statement at transformer :remove clauses of select
Error when parsing the statement at transformer :remove clauses of select
Error when parsing the statement at transformer :remove rows of an insert statement
Error when parsing the statement at transformer :remove rows of an insert statement
Error when parsing the statement at transformer :remove rows of an insert statement
Error when parsing the statement at transformer :remove columns of a select
Error when parsing the statement at transformer :remove columns of a select
Error when parsing the statement at transformer :remove columns of a select
Error when parsing the statement at transformer :remove elements of expression lists
Error when parsing the statement at transformer :remove elements of expression lists
Error when parsing the statement at transformer :remove elements of expression lists
Error when parsing the statement at transformer :simplify expressions. e.g. a + b -> a
Error when parsing the statement at transformer :simplify expressions. e.g. a + b -> a
Error when parsing the statement at transformer :simplify expressions. e.g. a + b -> a
Error when parsing the statement at transformer :simplify constant expressions
Error when parsing the statement at transformer :simplify constant expressions
Error when parsing the statement at transformer :simplify constant expressions
java.lang.AssertionError: **Found a potential bug**
        at sqlancer.Main$DBMSExecutor.run(Main.java:473)
        at sqlancer.Main$2.run(Main.java:645)
        at sqlancer.Main$2.runThread(Main.java:627)
        at sqlancer.Main$2.run(Main.java:618)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
--java.lang.AssertionError: Found a potential bug
--      at sqlancer.Main$DBMSExecutor.run(Main.java:473)
--      at sqlancer.Main$2.run(Main.java:645)
--      at sqlancer.Main$2.runThread(Main.java:627)
--      at sqlancer.Main$2.run(Main.java:618)
--      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--      at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: 2023/10/30 12:07:56
-- Database: database5
-- Database version: 3.43.2
-- seed value: 1698667565056
CREATE VIRTUAL TABLE rt0 USING rtree_i32(c0, c1, c2);
CREATE VIRTUAL TABLE rt1 USING rtree(c0, c1, c2, c3, c4);
INSERT OR IGNORE INTO rt1(c3, c2, c1, c4) VALUES ('-9223372036854775808', NULL, NULL, 0.582);
CREATE VIEW  IF NOT EXISTS v0(c0) AS SELECT DISTINCT (+ (((rt1.c0)*(rt1.c1)))) FROM rt1 WHERE (0.714);
INSERT OR ROLLBACK INTO rt0(c0) VALUES (x'');`
```

**Comment by mrigger** [comment] 2023-11-05 21:59
This seems to be a bug in the experimental reducer (see https://github.com/sqlancer/sqlancer/blob/cddff69308e9bcdbf0ed9abc5b77b57590431ff7/src/sqlancer/Main.java#L473). @ColinYoungTaro or @oraluben any ideas on how to address it?

**Comment by oraluben** [comment] 2023-11-06 06:27
The `Error when parsing ` lines are debug messages of reducer and can be safely ignored; the "potential bug" message is expected and indicates the reducer think it has get a minimal reproducer, which would be in the reducer log. You could go check `logs/<db>/reduce` for more information. @Syang111 

I've updated the message in https://github.com/sqlancer/sqlancer/pull/892, cc @mrigger

**Comment by ColinYoungTaro** [comment] 2023-11-07 11:30
The warning occurs because a transformation can't be initialized. 
Currently most transformations requires `JSQLParser` to parse the statement. If the parser failed to do so, the reducer will print the message and skipped this pass. 
The `RoundDoubleConstant` doesn't rely on the parser thus no relevant error messages are printed.

**Comment by oraluben** [comment] 2023-11-08 13:51
I'll close it for now, feel free to reopen it or submit new issues if you have more questions or thoughts about the reducer!

**Closed by oraluben** 2023-11-08 13:51 UTC
